---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.18.12-1

platforms:
- name: ubuntu-14.04
- name: ubuntu-12.04

suites:
- name: recursor
  run_list:
    - recipe[pdns::default]
  attributes:
- name: authoritative_source
  run_list:
    - recipe[pdns::default]
  attributes:
    pdns:
      build_method: source
      flavor: authoritative
      source:
        backends:
          - gpgsql
          - bind
      authoritative:
        backends:
          - gmysql
- name: backend_pgsql_source
  run_list:
    - recipe[postgresql::server]
    - recipe[pdns::default]
  attributes:
    pdns:
      build_method: source
      flavor: authoritative
      authoritative:
        backends:
          - gpgsql
        config:
          launch: gpgsql
    postgresql:
      password:
        postgres: wadus
- name: backend_pgsql_package
  run_list:
    - recipe[postgresql::server]
    - recipe[pdns::default]
  attributes:
    pdns:
      build_method: package
      flavor: authoritative
      package:
        backends:
        - gpgsql
        config:
          launch: gpgsql
    postgresql:
      password:
        postgres: wadus
- name: slave_source
  run_list:
    - recipe[pdns::default]
  attributes: 
    pdns:
      build_method: source
      flavor: slave
- name: slave_package
  run_list:
    - recipe[pdns::default]
  attributes:
    pdns:
      build_method: package
      flavor: slave

