name             'pdns'
maintainer       'DNSimple Corp'
maintainer_email 'ops@dnsimple.com'
license          'Apache-2.0'
description      'Installs/Configures PowerDNS Recursor and Authoritative server'
version          '8.0.0'
source_url       'https://github.com/dnsimple/chef-pdns'
issues_url       'https://github.com/dnsimple/chef-pdns/issues'

chef_version '>= 15'

supports 'ubuntu', '>= 18.04'
supports 'debian', '>= 9.0'
supports 'centos', '>= 7.0'
supports 'redhat', '>= 7.0'
